@startuml
title WarmHouse UserController Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

class User {
  +int id
  +String name
  +String email
  +List<House> houses
  +void register()
  +void login()
}

class House {
  +int id
  +String name
  +List<Device> devices
  +void add()
  +void remove()
}

abstract class Device {
  +int id
  +String name
  +void add()
  +void remove()
}

User "1" -- "0..*" House : has
House "1" -- "0..*" Device : has

@enduml


